add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
$aux_dir = '.';
$out_dir = '.';
sub makeglo2gls {
    my ($base_name) = @_;
    system("makeindex -s basic.gst -o \"$base_name.gls\" \"$base_name.glo\"");
}

$xelatex = 'xelatex -shell-escape %O %S';
$xdvipdfmx = 'xdvipdfmx -E -o %D %O %S';
